# Generated by Django 5.1.4 on 2025-01-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0002_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=' ', max_length=64),
            preserve_default=False,
        ),
    ]
