# Generated by Django 5.1.4 on 2025-01-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0003_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
