# Generated by Django 5.1.4 on 2025-01-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0004_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to='mainapi.user'),
        ),
    ]
